// <auto-generated />
namespace BigBangBlockchainGame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address));
        
        string IMigrationMetadata.Id
        {
            get { return "201612021520586_Address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
